/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package retofinal;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author dam117
 */
public class LlaveDificil extends javax.swing.JFrame {

    /**
     * Creates new form LlaveDificil
     */
    
    private int acu = 0;
    private int salas = 0;  
    
    public LlaveDificil() {
        initComponents();
        actualizarLabel();
    }
    
    private void actualizarLabel() {
        Random random = new Random();
        int num1 = random.nextInt(50) + 1;
        int num2 = random.nextInt(30) + 1;
        int num3 = random.nextInt(40) + 1;
        int num4 = random.nextInt(500) + 1;
        int num5;
        do {
            num5 = random.nextInt(100) + 1;
        } while (num4 % num5 != 0); // Asegura que num4 es divisible por num5

        int num6 = random.nextInt(50) + 1;

        jLabelNum1.setText(String.valueOf(num1));
        jLabelNum2.setText(String.valueOf(num2));
        jLabelNum3.setText(String.valueOf(num3));
        jLabelNum4.setText(String.valueOf(num4));
        jLabelNum5.setText(String.valueOf(num5));
        jLabelNum6.setText(String.valueOf(num6));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNum1 = new javax.swing.JLabel();
        jLabelSigno1 = new javax.swing.JLabel();
        jLabelNum2 = new javax.swing.JLabel();
        jLabelsigno2 = new javax.swing.JLabel();
        jLabelNum3 = new javax.swing.JLabel();
        jLabelSigno3 = new javax.swing.JLabel();
        jTextFieldResultado1 = new javax.swing.JTextField();
        jLabelNum4 = new javax.swing.JLabel();
        jLabelSigno4 = new javax.swing.JLabel();
        jLabelNum5 = new javax.swing.JLabel();
        jLabelSigno5 = new javax.swing.JLabel();
        jLabelNum6 = new javax.swing.JLabel();
        jLabelSigno6 = new javax.swing.JLabel();
        jTextFieldResultado2 = new javax.swing.JTextField();
        jButtonInsertarDificil = new javax.swing.JButton();
        jLabelFondoLlaveDificil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNum1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum1.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum1.setText("6");
        jPanel1.add(jLabelNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 60));

        jLabelSigno1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno1.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno1.setText("/");
        jPanel1.add(jLabelSigno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 20, 40));

        jLabelNum2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum2.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum2.setText("3");
        jPanel1.add(jLabelNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 46, 40, 50));

        jLabelsigno2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelsigno2.setForeground(new java.awt.Color(240, 240, 240));
        jLabelsigno2.setText("x");
        jPanel1.add(jLabelsigno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 30, 40));

        jLabelNum3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum3.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum3.setText("9");
        jPanel1.add(jLabelNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 46, 30, 50));

        jLabelSigno3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno3.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno3.setText("=");
        jPanel1.add(jLabelSigno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 30, 40));

        jTextFieldResultado1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanel1.add(jTextFieldResultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 40, 50));

        jLabelNum4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum4.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum4.setText("5");
        jPanel1.add(jLabelNum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        jLabelSigno4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno4.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno4.setText("/");
        jPanel1.add(jLabelSigno4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jLabelNum5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum5.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum5.setText("2");
        jPanel1.add(jLabelNum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        jLabelSigno5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno5.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno5.setText("x");
        jPanel1.add(jLabelSigno5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 30, -1));

        jLabelNum6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum6.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum6.setText("8");
        jPanel1.add(jLabelNum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jLabelSigno6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno6.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno6.setText("=");
        jPanel1.add(jLabelSigno6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jTextFieldResultado2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextFieldResultado2.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jTextFieldResultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 40, 50));

        jButtonInsertarDificil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonInsertarDificil.setText("Insertar");
        jButtonInsertarDificil.setBorder(null);
        jButtonInsertarDificil.setBorderPainted(false);
        jButtonInsertarDificil.setContentAreaFilled(false);
        jButtonInsertarDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarDificilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInsertarDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 160, 160));

        jLabelFondoLlaveDificil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LlaveNivelDificil7.png"))); // NOI18N
        jPanel1.add(jLabelFondoLlaveDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarDificilActionPerformed
        try {
            int p1 = Integer.parseInt(jLabelNum1.getText());
            int p2 = Integer.parseInt(jLabelNum2.getText());
            int p3 = Integer.parseInt(jLabelNum3.getText());
            int p4 = Integer.parseInt(jLabelNum4.getText());
            int p5 = Integer.parseInt(jLabelNum5.getText());
            int p6 = Integer.parseInt(jLabelNum6.getText());

            int respuesta1Usuario = Integer.parseInt(jTextFieldResultado1.getText());
            int respuesta2Usuario = Integer.parseInt(jTextFieldResultado2.getText());

            int respCorrecta1 = p1 + p2 * p3;
            int respCorrecta2 = p4 / p5 * p6;

            if (respuesta1Usuario == respCorrecta1 && respuesta2Usuario == respCorrecta2) {
                JOptionPane.showMessageDialog(this, "Respuesta correcta");
                actualizarLabel();
                salas=+1;
                setVisible(false);
                new PuertaDificil().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Respuesta Incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
                acu++;
                if (acu == 3) {
                    actualizarLabel();
                    acu = 0;
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa solo números válidos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonInsertarDificilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LlaveDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LlaveDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LlaveDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LlaveDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LlaveDificil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertarDificil;
    private javax.swing.JLabel jLabelFondoLlaveDificil;
    private javax.swing.JLabel jLabelNum1;
    private javax.swing.JLabel jLabelNum2;
    private javax.swing.JLabel jLabelNum3;
    private javax.swing.JLabel jLabelNum4;
    private javax.swing.JLabel jLabelNum5;
    private javax.swing.JLabel jLabelNum6;
    private javax.swing.JLabel jLabelSigno1;
    private javax.swing.JLabel jLabelSigno3;
    private javax.swing.JLabel jLabelSigno4;
    private javax.swing.JLabel jLabelSigno5;
    private javax.swing.JLabel jLabelSigno6;
    private javax.swing.JLabel jLabelsigno2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldResultado1;
    private javax.swing.JTextField jTextFieldResultado2;
    // End of variables declaration//GEN-END:variables
}
