/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package retofinal;

import static java.lang.Math.random;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dam117
 */
public class LlaveFacil extends javax.swing.JFrame {

    /**
     * Creates new form LlaveMedio
     */
    
    private int acu = 0;
    private int salas = 0;
    private List<Icon> imagenRandom;
    private Random random = new Random();
    
    private LlaveFacil ll = new LlaveFacil();
    private String numero1 = "" + ll.getNum1();
    private String numero2 = "" + ll.getNum2();
    private String numero3 = "" + ll.getNum3();

    private String numero4 = "" + ll.getNum4();
    private String numero5 = "" + ll.getNum5();
    private String numero6 = "" + ll.getNum6();

    private String numero7 = "" + ll.getNum7();
    private String numero8 = "" + ll.getNum8();
    private String numero9 = "" + ll.getNum9();
    
    public LlaveFacil() {
        initComponents();
        iniciarLabel();
        actualizarLabel();
    }
    
    private void iniciarLabel() {
        jLabelNum1.setText(numero1);
        jLabelNum2.setText(numero2);
        jLabelNum3.setText(numero3);

        jLabelNum4.setText(numero4);
        jLabelNum5.setText(numero5);
        jLabelNum6.setText(numero6);

        jLabelNum7.setText(numero7);
        jLabelNum8.setText(numero8);
        jLabelNum9.setText(numero9);

    }
    
    private void actualizarLabel() {
        Random random = new Random();
        boolean verificado = false;
        
        int num1 = random.nextInt(50) + 1;
        int num2 = random.nextInt(30) + 1;
        int num3 = random.nextInt(40) + 1;
        int num4 = random.nextInt(500) + 1;
        int num5;
        do {
            num5 = random.nextInt(100) + 1;
        } while (num4 % num5 != 0); // Asegura que num4 es divisible por num5

        int num6 = random.nextInt(50) + 1;
        int num7 = random.nextInt(50) + 1;
        int num8 = random.nextInt(50) + 1;
        int num9;
        
        do {
            num9 = random.nextInt(100) + 1;
        } while (num8 % num9 != 0);
        

        jLabelNum1.setText(String.valueOf(num1));
        jLabelNum2.setText(String.valueOf(num2));
        jLabelNum3.setText(String.valueOf(num3));
        jLabelNum4.setText(String.valueOf(num4));
        jLabelNum5.setText(String.valueOf(num5));
        jLabelNum6.setText(String.valueOf(num6));
        jLabelNum6.setText(String.valueOf(num7));
        jLabelNum6.setText(String.valueOf(num8));
        jLabelNum6.setText(String.valueOf(num9));
    }
    
    private void initCustomComponents() {
        imagenRandom = new ArrayList<>();
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelFacil.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelFacil.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelMedio.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelMedio.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelMedio.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelMedio.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelMedio.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelMedio.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelMedio.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelMedio.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelDificil.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelDificil.png")));
        imagenRandom.add(new ImageIcon(getClass().getResource("/Imagenes/LlaveNivelDificil.png")));
        cambiarPuerta();
    }
    
    private void cambiarPuerta() {
        int index = random.nextInt(imagenRandom.size());
        jLabelFondoLlaveFacil.setIcon(imagenRandom.get(index));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNum1 = new javax.swing.JLabel();
        jLabelSigno1 = new javax.swing.JLabel();
        jLabelNum2 = new javax.swing.JLabel();
        jLabelsigno2 = new javax.swing.JLabel();
        jLabelNum3 = new javax.swing.JLabel();
        jLabelSigno3 = new javax.swing.JLabel();
        jTextFieldResultado1 = new javax.swing.JTextField();
        jLabelNum4 = new javax.swing.JLabel();
        jLabelSigno4 = new javax.swing.JLabel();
        jLabelNum5 = new javax.swing.JLabel();
        jLabelSigno5 = new javax.swing.JLabel();
        jLabelNum6 = new javax.swing.JLabel();
        jLabelSigno6 = new javax.swing.JLabel();
        jTextFieldResultado2 = new javax.swing.JTextField();
        jButtonInsertarDificil = new javax.swing.JButton();
        jLabelNum7 = new javax.swing.JLabel();
        jLabelSigno7 = new javax.swing.JLabel();
        jLabelNum8 = new javax.swing.JLabel();
        jLabelSigno8 = new javax.swing.JLabel();
        jLabelNum9 = new javax.swing.JLabel();
        jLabelSigno9 = new javax.swing.JLabel();
        jTextFieldResultado3 = new javax.swing.JTextField();
        jLabelFondoLlaveFacil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNum1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum1.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum1.setText("6");
        jPanel1.add(jLabelNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 60));

        jLabelSigno1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno1.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno1.setText("+");
        jPanel1.add(jLabelSigno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 30, 40));

        jLabelNum2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum2.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum2.setText("3");
        jPanel1.add(jLabelNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 40, 60));

        jLabelsigno2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelsigno2.setForeground(new java.awt.Color(240, 240, 240));
        jLabelsigno2.setText("x");
        jPanel1.add(jLabelsigno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 30, 40));

        jLabelNum3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum3.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum3.setText("9");
        jPanel1.add(jLabelNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 30, 60));

        jLabelSigno3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno3.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno3.setText("=");
        jPanel1.add(jLabelSigno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 30, 40));

        jTextFieldResultado1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextFieldResultado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultado1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldResultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 40, 50));

        jLabelNum4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum4.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum4.setText("5");
        jPanel1.add(jLabelNum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        jLabelSigno4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno4.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno4.setText("/");
        jPanel1.add(jLabelSigno4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jLabelNum5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum5.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum5.setText("2");
        jPanel1.add(jLabelNum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        jLabelSigno5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno5.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno5.setText("x");
        jPanel1.add(jLabelSigno5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 30, -1));

        jLabelNum6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum6.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum6.setText("8");
        jPanel1.add(jLabelNum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        jLabelSigno6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno6.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno6.setText("=");
        jPanel1.add(jLabelSigno6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jTextFieldResultado2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextFieldResultado2.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jTextFieldResultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 40, 50));

        jButtonInsertarDificil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonInsertarDificil.setText("Insertar");
        jButtonInsertarDificil.setBorder(null);
        jButtonInsertarDificil.setBorderPainted(false);
        jButtonInsertarDificil.setContentAreaFilled(false);
        jButtonInsertarDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarDificilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInsertarDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 160, 160));

        jLabelNum7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum7.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum7.setText("5");
        jPanel1.add(jLabelNum7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 40));

        jLabelSigno7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno7.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno7.setText("-");
        jPanel1.add(jLabelSigno7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 30));

        jLabelNum8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum8.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum8.setText("7");
        jPanel1.add(jLabelNum8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 40));

        jLabelSigno8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno8.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno8.setText("/");
        jPanel1.add(jLabelSigno8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, 40));

        jLabelNum9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNum9.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNum9.setText("1");
        jPanel1.add(jLabelNum9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, 40));

        jLabelSigno9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno9.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno9.setText("=");
        jPanel1.add(jLabelSigno9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, 40));

        jTextFieldResultado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultado3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldResultado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 40, 50));

        jLabelFondoLlaveFacil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LlaveNivelDificil7.png"))); // NOI18N
        jPanel1.add(jLabelFondoLlaveFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarDificilActionPerformed
        try {
            int p1 = Integer.parseInt(jLabelNum1.getText());
            int p2 = Integer.parseInt(jLabelNum2.getText());
            int p3 = Integer.parseInt(jLabelNum3.getText());
            
            int p4 = Integer.parseInt(jLabelNum4.getText());
            int p5 = Integer.parseInt(jLabelNum5.getText());
            int p6 = Integer.parseInt(jLabelNum6.getText());
            
            int p7 = Integer.parseInt(jLabelNum7.getText());
            int p8 = Integer.parseInt(jLabelNum8.getText());
            int p9 = Integer.parseInt(jLabelNum9.getText());

            int respuesta1Usuario = Integer.parseInt(jTextFieldResultado1.getText());
            int respuesta2Usuario = Integer.parseInt(jTextFieldResultado2.getText());
            int respuesta3Usuario = Integer.parseInt(jTextFieldResultado3.getText());

            int respCorrecta1 = p1 + p2 * p3;
            int respCorrecta2 = p4 / p5 * p6;
            int respCorrecta3 = p7 - p8 / p9;

            if (respuesta1Usuario == respCorrecta1 && respuesta2Usuario == respCorrecta2 && respuesta3Usuario == respCorrecta3) {
                JOptionPane.showMessageDialog(this, "Respuesta correcta");
                actualizarLabel();
                salas=+1;
                setVisible(false);
                new PuertaDificil().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Respuesta Incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
                acu++;
                if (acu == 3) {
                    setVisible(false);
                    new FinPartida().setVisible(true);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa solo números válidos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonInsertarDificilActionPerformed

    private void jTextFieldResultado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultado3ActionPerformed

    private void jTextFieldResultado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultado1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LlaveFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LlaveFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LlaveFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LlaveFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LlaveFacil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertarDificil;
    private javax.swing.JLabel jLabelFondoLlaveFacil;
    private javax.swing.JLabel jLabelNum1;
    private javax.swing.JLabel jLabelNum2;
    private javax.swing.JLabel jLabelNum3;
    private javax.swing.JLabel jLabelNum4;
    private javax.swing.JLabel jLabelNum5;
    private javax.swing.JLabel jLabelNum6;
    private javax.swing.JLabel jLabelNum7;
    private javax.swing.JLabel jLabelNum8;
    private javax.swing.JLabel jLabelNum9;
    private javax.swing.JLabel jLabelSigno1;
    private javax.swing.JLabel jLabelSigno3;
    private javax.swing.JLabel jLabelSigno4;
    private javax.swing.JLabel jLabelSigno5;
    private javax.swing.JLabel jLabelSigno6;
    private javax.swing.JLabel jLabelSigno7;
    private javax.swing.JLabel jLabelSigno8;
    private javax.swing.JLabel jLabelSigno9;
    private javax.swing.JLabel jLabelsigno2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldResultado1;
    private javax.swing.JTextField jTextFieldResultado2;
    private javax.swing.JTextField jTextFieldResultado3;
    // End of variables declaration//GEN-END:variables

    private String getNum1() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String getNum2() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String getNum3() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String getNum4() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String getNum5() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String getNum6() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String getNum7() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String getNum8() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String getNum9() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
