/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package retofinal;

import java.util.List;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.JOptionPane;


/**
 *
 * @author dam117
 */
public class LlaveMedio extends javax.swing.JFrame {

    /**
     * Creates new form LlaveMedio
     */
    
    private int acu = 0;
    private int salas = 0;  
    private List<Icon> imagenRandom;
    private Random random = new Random();
    
    private PreguntasMedio p = new PreguntasMedio();
    //Datos primera pregunta
    private String numero1 = "√" + p.getNum1();
    private String numero2 = "√" + p.getNum2();
    private String numero3 = "√" + p.getNum3();
    private String numero4 = "√" + p.getNum4();
    
    //Datos segunda pregunta1w2
    private String numero5 = "√" + p.getNum5();
    private String numero6 = "√" + p.getNum6();
    
    //Datos tercera pregunta
    private String numero7 = "√" + p.getNum7();
    private String numero8 = "√" + p.getNum8();
    
    private void iniciarLabel() {
        jLabelRaizSola1.setText(numero1);
        jLabelRaizSola2.setText(numero2);
        jLabelRaizSola3.setText(numero3);
        jLabelRaizSola4.setText(numero4);

        jLabelPrimeraRaizSuma.setText(numero5);
        jLabelSegundaRaizSuma.setText(numero6);

        jLabelPrimeraRaizMulti.setText(numero7);
        jLabelSegundaRaizMulti.setText(numero8);
    }
    
    public LlaveMedio() {
        initComponents();
        iniciarLabel();
        actualizarLabel();
    }
    
    private void actualizarLabel() {
        Random r1 = new Random();
        
        //primera raiz
        int num1 = generaRaiz(50, r1.nextInt(250) + 1);
        int num2 = generaRaiz(30, r1.nextInt(230) + 1);
        int num3 = generaRaiz(40, r1.nextInt(240) + 1);
        int num4 = generaRaiz(20, r1.nextInt(210) + 1);
        String label1 = "√" + num1;
        String label2 = "√" + num2;
        String label3 = "√" + num2;
        String label4 = "√" + num4;
        
        int num5 = generaRaiz(45, r1.nextInt(220) + 1);
        int num6 = generaRaiz(40, r1.nextInt(215) + 1);
        String label5 = "√" + num5;
        String label6 = "√" + num6;
        
        int num7 = generaRaiz(36, r1.nextInt(100) + 1);
        int num8 = generaRaiz(25, r1.nextInt(140) + 1);
        String label7 = "√" + num7;
        String label8 = "√" + num8;
        
        //coversion de los label
        //primera raiz sola
        jLabelRaizSola1.setText(label1);
        //segunda raiz sola
        jLabelRaizSola2.setText(label2);
        //tercera raiz sola
        jLabelRaizSola3.setText(label3);
        //cuarta raiz sola
        jLabelRaizSola4.setText(label4);
        
        // suma
        jLabelPrimeraRaizSuma.setText(label5);
        jLabelSegundaRaizSuma.setText(label6);
        
        // multiplicacion
        jLabelPrimeraRaizMulti.setText(label7);
        jLabelSegundaRaizMulti.setText(label8);
    }
    
    public static String quitarSimboloRaiz(String s) {
        if (s.startsWith("√")) {
            return s.substring(1);
        } else {
            return s;
        } 
    }
    
    private static int generaRaiz(int min, int max) {
        Random rand = new Random();
        int numRand;
        int raizExacta = 0;

        do {
            numRand = rand.nextInt(max - min + 1) + min;
            if (esRaizExacta(numRand)) {
                            raizExacta = numRand;
            }
        } while (raizExacta == 0);

        return raizExacta;      
    }
    
    private static boolean esRaizExacta(int n) {
        int sqrt = (int) Math.sqrt(n);
        return sqrt * sqrt == n;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPrimeraRaizSuma = new javax.swing.JLabel();
        jLabelSigno1 = new javax.swing.JLabel();
        jLabelSegundaRaizSuma = new javax.swing.JLabel();
        jLabelIgual1 = new javax.swing.JLabel();
        jLabelRaizSola1 = new javax.swing.JLabel();
        jLabelIgual2 = new javax.swing.JLabel();
        jTextFieldRespuestaRaizSola1 = new javax.swing.JTextField();
        jLabelPrimeraRaizMulti = new javax.swing.JLabel();
        jLabelSigno2 = new javax.swing.JLabel();
        jLabelSegundaRaizMulti = new javax.swing.JLabel();
        jLabelIgual5 = new javax.swing.JLabel();
        jLabelRaizSola4 = new javax.swing.JLabel();
        jLabelIgual6 = new javax.swing.JLabel();
        jTextFieldRespuestaMulti = new javax.swing.JTextField();
        jButtonInsertarDificil = new javax.swing.JButton();
        jTextFieldRespuestaSuma = new javax.swing.JTextField();
        jTextFieldRespuestaRaizSola4 = new javax.swing.JTextField();
        jTextFieldRespuestaRaizSola3 = new javax.swing.JTextField();
        jTextFieldRespuestaRaizSola2 = new javax.swing.JTextField();
        jLabelIgual3 = new javax.swing.JLabel();
        jLabelRaizSola2 = new javax.swing.JLabel();
        jLabelIgual4 = new javax.swing.JLabel();
        jLabelRaizSola3 = new javax.swing.JLabel();
        jLabelFondoLlaveDificil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPrimeraRaizSuma.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelPrimeraRaizSuma.setForeground(new java.awt.Color(240, 240, 240));
        jLabelPrimeraRaizSuma.setText("6");
        jPanel1.add(jLabelPrimeraRaizSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 60));

        jLabelSigno1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno1.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno1.setText("+");
        jPanel1.add(jLabelSigno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 30, 40));

        jLabelSegundaRaizSuma.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSegundaRaizSuma.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSegundaRaizSuma.setText("3");
        jPanel1.add(jLabelSegundaRaizSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 46, 40, 50));

        jLabelIgual1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelIgual1.setForeground(new java.awt.Color(240, 240, 240));
        jLabelIgual1.setText("=");
        jPanel1.add(jLabelIgual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 30, 40));

        jLabelRaizSola1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelRaizSola1.setForeground(new java.awt.Color(240, 240, 240));
        jLabelRaizSola1.setText("9");
        jPanel1.add(jLabelRaizSola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 30, 50));

        jLabelIgual2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelIgual2.setForeground(new java.awt.Color(240, 240, 240));
        jLabelIgual2.setText("=");
        jPanel1.add(jLabelIgual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 30, 40));

        jTextFieldRespuestaRaizSola1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextFieldRespuestaRaizSola1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jTextFieldRespuestaRaizSola1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 40, 50));

        jLabelPrimeraRaizMulti.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelPrimeraRaizMulti.setForeground(new java.awt.Color(240, 240, 240));
        jLabelPrimeraRaizMulti.setText("5");
        jPanel1.add(jLabelPrimeraRaizMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        jLabelSigno2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSigno2.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSigno2.setText("*");
        jPanel1.add(jLabelSigno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jLabelSegundaRaizMulti.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSegundaRaizMulti.setForeground(new java.awt.Color(240, 240, 240));
        jLabelSegundaRaizMulti.setText("2");
        jPanel1.add(jLabelSegundaRaizMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        jLabelIgual5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelIgual5.setForeground(new java.awt.Color(240, 240, 240));
        jLabelIgual5.setText("=");
        jPanel1.add(jLabelIgual5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 30, -1));

        jLabelRaizSola4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelRaizSola4.setForeground(new java.awt.Color(240, 240, 240));
        jLabelRaizSola4.setText("8");
        jPanel1.add(jLabelRaizSola4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        jLabelIgual6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelIgual6.setForeground(new java.awt.Color(240, 240, 240));
        jLabelIgual6.setText("=");
        jPanel1.add(jLabelIgual6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        jTextFieldRespuestaMulti.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextFieldRespuestaMulti.setForeground(new java.awt.Color(240, 240, 240));
        jTextFieldRespuestaMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRespuestaMultiActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRespuestaMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 40, 50));

        jButtonInsertarDificil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonInsertarDificil.setText("Insertar");
        jButtonInsertarDificil.setBorder(null);
        jButtonInsertarDificil.setBorderPainted(false);
        jButtonInsertarDificil.setContentAreaFilled(false);
        jButtonInsertarDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarDificilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInsertarDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 160, 160));

        jTextFieldRespuestaSuma.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextFieldRespuestaSuma.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jTextFieldRespuestaSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 40, 50));

        jTextFieldRespuestaRaizSola4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextFieldRespuestaRaizSola4.setForeground(new java.awt.Color(240, 240, 240));
        jTextFieldRespuestaRaizSola4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRespuestaRaizSola4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRespuestaRaizSola4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 40, 50));

        jTextFieldRespuestaRaizSola3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextFieldRespuestaRaizSola3.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jTextFieldRespuestaRaizSola3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 40, 50));

        jTextFieldRespuestaRaizSola2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextFieldRespuestaRaizSola2.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(jTextFieldRespuestaRaizSola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 40, 50));

        jLabelIgual3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelIgual3.setForeground(new java.awt.Color(240, 240, 240));
        jLabelIgual3.setText("=");
        jPanel1.add(jLabelIgual3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 30, 20));

        jLabelRaizSola2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelRaizSola2.setForeground(new java.awt.Color(240, 240, 240));
        jLabelRaizSola2.setText("0");
        jPanel1.add(jLabelRaizSola2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 30, -1));

        jLabelIgual4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelIgual4.setForeground(new java.awt.Color(240, 240, 240));
        jLabelIgual4.setText("=");
        jPanel1.add(jLabelIgual4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabelRaizSola3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelRaizSola3.setForeground(new java.awt.Color(240, 240, 240));
        jLabelRaizSola3.setText("9");
        jPanel1.add(jLabelRaizSola3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, 50));

        jLabelFondoLlaveDificil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LlaveNivelDificil7.png"))); // NOI18N
        jPanel1.add(jLabelFondoLlaveDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarDificilActionPerformed
        String result1Usu = jTextFieldRespuestaRaizSola4.getText();
        String result2Usu = jTextFieldRespuestaRaizSola2.getText();
        String result3Usu = jTextFieldRespuestaRaizSola3.getText();
        String result4Usu = jTextFieldRespuestaRaizSola3.getText();
        String result5Usu = jTextFieldRespuestaSuma.getText();
        String result6Usu = jTextFieldRespuestaMulti.getText();

        //para obtener el result1Usu aleatorio
        String label1 = jLabelRaizSola1.getText();
        String label2 = jLabelRaizSola2.getText();
        String label3 = jLabelRaizSola3.getText();
        String label4 = jLabelRaizSola4.getText();
        
        String label5 = jLabelPrimeraRaizSuma.getText();
        String label6 = jLabelSegundaRaizSuma.getText();

        String label7 = jLabelPrimeraRaizMulti.getText();
        String label8 = jLabelSegundaRaizMulti.getText();

        //string a entero
        // Raices solas
        int p1 = Integer.parseInt(quitarSimboloRaiz(label1));
        int p2 = Integer.parseInt(quitarSimboloRaiz(label2));
        int p3 = Integer.parseInt(quitarSimboloRaiz(label3));
        int p4 = Integer.parseInt(quitarSimboloRaiz(label4));
        // Raices suma
        int p5 = Integer.parseInt(quitarSimboloRaiz(label5));
        int p6 = Integer.parseInt(quitarSimboloRaiz(label6));
        // Raices multiplicacion
        int p7 = Integer.parseInt(quitarSimboloRaiz(label7));
        int p8 = Integer.parseInt(quitarSimboloRaiz(label8));

        //obtener respuesta1Usuario
        // respuestas raices solas
        int respuesta1Usuario = Integer.parseInt(result1Usu);
        int respuesta2Usuario = Integer.parseInt(result2Usu);
        int respuesta3Usuario = Integer.parseInt(result3Usu);
        int respuesta4Usuario = Integer.parseInt(result1Usu);
        // Respuestas operaciones
        int respuesta5Usuario = Integer.parseInt(result2Usu);
        int respuesta6Usuario = Integer.parseInt(result3Usu);

        //Calcular las respuestas correctas
        int respCorrecta1 = (int) Math.sqrt(p1);
        int respCorrecta2 = (int) Math.sqrt(p2);
        int respCorrecta3 = (int) Math.sqrt(p3);
        int respCorrecta4 = (int) Math.sqrt(p4);
        int respCorrecta5 = (int) Math.sqrt(p5) + (int) Math.sqrt(p6);
        int respCorrecta6 = (int) Math.sqrt(p7) * (int) Math.sqrt(p8);

        if (respuesta1Usuario == respCorrecta1 && respuesta2Usuario == 
                respCorrecta2 && respuesta3Usuario == respCorrecta3 && 
                respuesta4Usuario == respCorrecta4 && respuesta5Usuario == 
                respCorrecta5 && respuesta6Usuario == respCorrecta6) {
            JOptionPane.showMessageDialog(this, "respuesta correcta");
            actualizarLabel();
        } else {
            JOptionPane.showMessageDialog(this, "Respuesta "
                    + "Incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            acu++;
            if (acu == 3) {
                setVisible(false);
                new FinPartida().setVisible(true);
            }
            
        }
    }//GEN-LAST:event_jButtonInsertarDificilActionPerformed

    private void jTextFieldRespuestaRaizSola4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRespuestaRaizSola4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRespuestaRaizSola4ActionPerformed

    private void jTextFieldRespuestaMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRespuestaMultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRespuestaMultiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LlaveMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LlaveMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LlaveMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LlaveMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LlaveMedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertarDificil;
    private javax.swing.JLabel jLabelFondoLlaveDificil;
    private javax.swing.JLabel jLabelIgual1;
    private javax.swing.JLabel jLabelIgual2;
    private javax.swing.JLabel jLabelIgual3;
    private javax.swing.JLabel jLabelIgual4;
    private javax.swing.JLabel jLabelIgual5;
    private javax.swing.JLabel jLabelIgual6;
    private javax.swing.JLabel jLabelPrimeraRaizMulti;
    private javax.swing.JLabel jLabelPrimeraRaizSuma;
    private javax.swing.JLabel jLabelRaizSola1;
    private javax.swing.JLabel jLabelRaizSola2;
    private javax.swing.JLabel jLabelRaizSola3;
    private javax.swing.JLabel jLabelRaizSola4;
    private javax.swing.JLabel jLabelSegundaRaizMulti;
    private javax.swing.JLabel jLabelSegundaRaizSuma;
    private javax.swing.JLabel jLabelSigno1;
    private javax.swing.JLabel jLabelSigno2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldRespuestaMulti;
    private javax.swing.JTextField jTextFieldRespuestaRaizSola1;
    private javax.swing.JTextField jTextFieldRespuestaRaizSola2;
    private javax.swing.JTextField jTextFieldRespuestaRaizSola3;
    private javax.swing.JTextField jTextFieldRespuestaRaizSola4;
    private javax.swing.JTextField jTextFieldRespuestaSuma;
    // End of variables declaration//GEN-END:variables
}
