/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package retofinal;

import com.sun.source.tree.BreakTree;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JButton;


/**
 *
 * @author dam126
 */
public class PreguntaDificil extends javax.swing.JFrame {

    /**
     * Creates new form Preguntas
     */
    private PreguntasDificil p = new PreguntasDificil(); 
    private String numero1 = "" + p.getNum1();
    private String numero2 = "" + p.getNum2();
    private String numero3 = "" + p.getNum3();

    private int acu = 0;

    public PreguntaDificil() {
        initComponents();
        iniciarLabel();
    }
    
    public void TransparenciaBotones() {
        
        jButtonUsarLlaveDificil.setContentAreaFilled(false);
        
        
    }
    
    private List<Icon> imagenDificil;
    private Random random;
    
    public void randomPuerta() {
        
        imagenDificil = new ArrayList<Icon>();
        imagenDificil.add(new ImageIcon(""));
        imagenDificil.add(new ImageIcon(""));
        
        random = new Random();
        
        cambiarPuerta();
        
    }
    
    private void cambiarPuerta() {
        
        int index = random.nextInt(imagenDificil.size());
        puerta1.setIcon(imagenDificil.get(index));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jButtonSalirDificil = new java.awt.Button();
        jButtonUsarLlaveDificil = new java.awt.Button();
        puerta1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CalculESO - Facil");
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalirDificil.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jButtonSalirDificil.setLabel("Salir");
        jButtonSalirDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirDificilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalirDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 660, 100, 30));

        jButtonUsarLlaveDificil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonUsarLlaveDificil.setFont(new java.awt.Font("Noto Mono", 0, 12)); // NOI18N
        jButtonUsarLlaveDificil.setLabel("Usar llave");
        jButtonUsarLlaveDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsarLlaveDificilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUsarLlaveDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, 100, 30));

        puerta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PuertaNivelDificil.png"))); // NOI18N
        jPanel1.add(puerta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUsarLlaveDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsarLlaveDificilActionPerformed
        setVisible(false);
        LlaveDificil l1 = new LlaveDificil();
        l1.setVisible(true);
    }//GEN-LAST:event_jButtonUsarLlaveDificilActionPerformed

    private void jButtonSalirDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirDificilActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonSalirDificilActionPerformed

    private void iniciarLabel() {
        jLabelnum1.setText(numero1);
        jLabelnum2.setText(numero2);
        jLabelnum3.setText(numero3);

    }

    private void actualizarLabel() {
        Random r1 = new Random();
        boolean verificado = false;
        
        //primera operacion, l1+l2*l3
        int num1 = r1.nextInt(50) + 1;
        int num2 = r1.nextInt(30) + 1;
        int num3 = r1.nextInt(40) + 1;
        String label1 = "" + num1;
        String label2 = "" + num2;
        String label3 = "" + num2;
        
        //segunda operacion, l4/l5*l6
        int num4;
        int num5;
        do {
            num4 = r1.nextInt(500) + 1;
            num5 = r1.nextInt(100) + 1;
            if (num4 % num5 == 0) {
                verificado = true;
            }
        } while (!verificado);
        
        //coversion de los label
        //primera operacion
        jLabelnum1.setText(label1);
        jLabelnum2.setText(label2);
        jLabelnum3.setText(label3);

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button jButtonSalirDificil;
    private java.awt.Button jButtonUsarLlaveDificil;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel puerta1;
    // End of variables declaration//GEN-END:variables
}
