/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package retofinal;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author dam126
 */
public class PreguntaFacil extends javax.swing.JFrame {

    /**
     * Creates new form Preguntas
     */
    private PreguntasFacil p = new PreguntasFacil();
    private String numero1 = "" + p.getNum1();
    private String numero2 = "" + p.getNum2();
    private String numero3 = "" + p.getNum3();

    private String numero4 = "" + p.getNum4();
    private String numero5 = "" + p.getNum5();
    private String numero6 = "" + p.getNum6();

    private String numero7 = "" + p.getNum7();
    private String numero8 = "" + p.getNum8();
    private String numero9 = "" + p.getNum9();

    private int acu = 0;

    public PreguntaFacil() {
        initComponents();
        iniciarLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAceptarPreguntas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRespuestaSumaMulti = new javax.swing.JTextField();
        signo2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelnum1 = new javax.swing.JLabel();
        jLabelnum6 = new javax.swing.JLabel();
        signo1 = new javax.swing.JLabel();
        jTextFieldRespuestaRestaDivi = new javax.swing.JTextField();
        signo5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelnum9div2 = new javax.swing.JLabel();
        jTextFieldRespuestaDiviMulti = new javax.swing.JTextField();
        signo3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelnum4div1 = new javax.swing.JLabel();
        jLabelnum5div1 = new javax.swing.JLabel();
        jLabelnum2 = new javax.swing.JLabel();
        signo4 = new javax.swing.JLabel();
        signo6 = new javax.swing.JLabel();
        jLabelnum3 = new javax.swing.JLabel();
        jLabelnum7resta1 = new javax.swing.JLabel();
        jLabelnum8div2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CalculESO - Facil");
        setBackground(new java.awt.Color(204, 255, 204));

        jButtonAceptarPreguntas.setText("Aceptar");
        jButtonAceptarPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarPreguntasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Operaciones:");

        jTextFieldRespuestaSumaMulti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldRespuestaSumaMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRespuestaSumaMultiActionPerformed(evt);
            }
        });

        signo2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        signo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signo2.setText("x");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("=");

        jLabelnum1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelnum6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        signo1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        signo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signo1.setText("+");

        jTextFieldRespuestaRestaDivi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldRespuestaRestaDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRespuestaRestaDiviActionPerformed(evt);
            }
        });

        signo5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        signo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signo5.setText("-");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("=");

        jLabelnum9div2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextFieldRespuestaDiviMulti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldRespuestaDiviMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRespuestaDiviMultiActionPerformed(evt);
            }
        });

        signo3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        signo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signo3.setText("/");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setText("=");

        jLabelnum4div1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelnum5div1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelnum2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        signo4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        signo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signo4.setText("x");

        signo6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        signo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signo6.setText("/");

        jLabelnum3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelnum7resta1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabelnum8div2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(signo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabelnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addComponent(jTextFieldRespuestaSumaMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(signo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelnum3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelnum7resta1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(signo5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabelnum8div2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(signo6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabelnum9div2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jTextFieldRespuestaRestaDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelnum4div1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(signo3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabelnum5div1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(signo4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabelnum6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldRespuestaDiviMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jButtonAceptarPreguntas)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signo1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signo2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRespuestaSumaMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelnum3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRespuestaDiviMulti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signo3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelnum4div1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelnum5div1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signo4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelnum6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelnum9div2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signo6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextFieldRespuestaRestaDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)))
                    .addComponent(jLabelnum7resta1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signo5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelnum8div2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButtonAceptarPreguntas)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarLabel() {
        jLabelnum1.setText(numero1);
        jLabelnum2.setText(numero2);
        jLabelnum3.setText(numero3);

        jLabelnum4div1.setText(numero4);
        jLabelnum5div1.setText(numero5);
        jLabelnum6.setText(numero6);

        jLabelnum7resta1.setText(numero7);
        jLabelnum8div2.setText(numero8);
        jLabelnum9div2.setText(numero9);

    }

    private void jButtonAceptarPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarPreguntasActionPerformed
        String result1Usu = jTextFieldRespuestaSumaMulti.getText();
        String result2Usu = jTextFieldRespuestaDiviMulti.getText();
        String result3Usu = jTextFieldRespuestaRestaDivi.getText();

        //para obtener el result1Usu aleatorio
        String label1 = jLabelnum1.getText();
        String label2 = jLabelnum2.getText();
        String label3 = jLabelnum3.getText();

        String label4 = jLabelnum4div1.getText();
        String label5 = jLabelnum5div1.getText();
        String label6 = jLabelnum6.getText();

        String label7 = jLabelnum7resta1.getText();
        String label8 = jLabelnum8div2.getText();
        String label9 = jLabelnum9div2.getText();

        //string a entero
        int p1 = Integer.parseInt(label1);
        int p2 = Integer.parseInt(label2);
        int p3 = Integer.parseInt(label3);

        int p4 = Integer.parseInt(label4);
        int p5 = Integer.parseInt(label5);
        int p6 = Integer.parseInt(label6);

        int p7 = Integer.parseInt(label7);
        int p8 = Integer.parseInt(label8);
        int p9 = Integer.parseInt(label9);

        //obtener respuesta1Usuario
        int respuesta1Usuario = Integer.parseInt(result1Usu);
        int respuesta2Usuario = Integer.parseInt(result2Usu);
        int respuesta3Usuario = Integer.parseInt(result3Usu);

        //verificar
        int respCorrecta1 = p2 * p3 + p1;
        int respCorrecta2 = p4 / p5 * p6;
        int respCorrecta3 = p7 - p8 / p9;

        if (respuesta1Usuario == respCorrecta1 && respuesta2Usuario == respCorrecta2
                && respuesta3Usuario == respCorrecta3) {
            JOptionPane.showMessageDialog(this, "respuesta correcta");
            actualizarLabel();
        } else {
            JOptionPane.showMessageDialog(this, "Respuesta "
                    + "Incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            acu++;
            if (acu == 3) {
                actualizarLabel();
                acu = 0;
            }
        }


    }//GEN-LAST:event_jButtonAceptarPreguntasActionPerformed

    private void actualizarLabel() {
        Random r1 = new Random();
        boolean verificado = false;
        
        //primera operacion, l1+l2*l3
        int num1 = r1.nextInt(50) + 1;
        int num2 = r1.nextInt(30) + 1;
        int num3 = r1.nextInt(40) + 1;
        String label1 = "" + num1;
        String label2 = "" + num2;
        String label3 = "" + num2;
        
        //segunda operacion, l4/l5*l6
        int num4;
        int num5;
        do {
            num4 = r1.nextInt(500) + 1;
            num5 = r1.nextInt(100) + 1;
            if (num4 % num5 == 0) {
                verificado = true;
            }
        } while (!verificado);
        int num6 = r1.nextInt(40) + 1;
        String label4 = "" + num4;
        String label5 = "" + num5;
        String label6 = "" + num6;
        
        //tercera operacion, l7-l8/l9
        int num7 = r1.nextInt(50) + 1;
        int num8;
        int num9;
        do {
            verificado = false;
            num8 = r1.nextInt(500) + 1;
            num9 = r1.nextInt(100) + 1;
            if (num8 % num9 == 0) {
                verificado = true;
            }
        } while (!verificado);
        String label7 = "" + num7;
        String label8 = "" + num8;
        String label9 = "" + num9;

        //coversion de los label
        //primera operacion
        jLabelnum1.setText(label1);
        jLabelnum2.setText(label2);
        jLabelnum3.setText(label3);
        //segunda operacion
        jLabelnum4div1.setText(label4);
        jLabelnum5div1.setText(label5);
        jLabelnum6.setText(label6);
        
        //tercera operacion
        jLabelnum7resta1.setText(label7);
        jLabelnum8div2.setText(label8);
        jLabelnum9div2.setText(label9);

    }

    private void jTextFieldRespuestaSumaMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRespuestaSumaMultiActionPerformed


    }//GEN-LAST:event_jTextFieldRespuestaSumaMultiActionPerformed

    private void jTextFieldRespuestaRestaDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRespuestaRestaDiviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRespuestaRestaDiviActionPerformed

    private void jTextFieldRespuestaDiviMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRespuestaDiviMultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRespuestaDiviMultiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptarPreguntas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelnum1;
    private javax.swing.JLabel jLabelnum2;
    private javax.swing.JLabel jLabelnum3;
    private javax.swing.JLabel jLabelnum4div1;
    private javax.swing.JLabel jLabelnum5div1;
    private javax.swing.JLabel jLabelnum6;
    private javax.swing.JLabel jLabelnum7resta1;
    private javax.swing.JLabel jLabelnum8div2;
    private javax.swing.JLabel jLabelnum9div2;
    private javax.swing.JTextField jTextFieldRespuestaDiviMulti;
    private javax.swing.JTextField jTextFieldRespuestaRestaDivi;
    private javax.swing.JTextField jTextFieldRespuestaSumaMulti;
    private javax.swing.JLabel signo1;
    private javax.swing.JLabel signo2;
    private javax.swing.JLabel signo3;
    private javax.swing.JLabel signo4;
    private javax.swing.JLabel signo5;
    private javax.swing.JLabel signo6;
    // End of variables declaration//GEN-END:variables
}
