/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package retofinal;

import com.sun.source.tree.BreakTree;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JButton;
/**
 *
 * @author dam117
 */
public class PuertaDificil extends javax.swing.JFrame {

    /**
     * Creates new form PreguntaDificil
     */
    private List<Icon> imagenDificil;
    private Random random = new Random();

    public PuertaDificil() {
        initComponents();
        initCustomComponents();
    }
    
    private void initCustomComponents() {
        imagenDificil = new ArrayList<>();
        imagenDificil.add(new ImageIcon(getClass().getResource("/Imagenes/imagen1.png")));
        imagenDificil.add(new ImageIcon(getClass().getResource("/Imagenes/imagen2.png")));
        cambiarPuerta();
    }
    
    private void cambiarPuerta() {
        int index = random.nextInt(imagenDificil.size());
        jLabelFondoPuertaDificil.setIcon(imagenDificil.get(index));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInutilFondo = new javax.swing.JPanel();
        jButtonSalirDificil = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        jLabelFondoPuertaDificil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelInutilFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalirDificil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoSalir.png"))); // NOI18N
        jButtonSalirDificil.setBorder(null);
        jButtonSalirDificil.setBorderPainted(false);
        jButtonSalirDificil.setContentAreaFilled(false);
        jButtonSalirDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirDificilActionPerformed(evt);
            }
        });
        PanelInutilFondo.add(jButtonSalirDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 60, 40));

        jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoLlave-removebg-preview.png"))); // NOI18N
        jButton.setBorder(null);
        jButton.setBorderPainted(false);
        jButton.setContentAreaFilled(false);
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        PanelInutilFondo.add(jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, -1, -1));

        jLabelFondoPuertaDificil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PuertaNivelDificil.png"))); // NOI18N
        PanelInutilFondo.add(jLabelFondoPuertaDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInutilFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInutilFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirDificilActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonSalirDificilActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        setVisible(false);
        LlaveDificil l1 = new LlaveDificil();
        l1.setVisible(true);
    }//GEN-LAST:event_jButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuertaDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuertaDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuertaDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuertaDificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuertaDificil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInutilFondo;
    private javax.swing.JButton jButton;
    private javax.swing.JButton jButtonSalirDificil;
    private javax.swing.JLabel jLabelFondoPuertaDificil;
    // End of variables declaration//GEN-END:variables
}
